# Generated by Django 3.2 on 2021-05-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=64)),
                ('mdp', models.CharField(max_length=64)),
                ('tel', models.IntegerField(max_length=10)),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
    ]
