# Generated by Django 3.2 on 2021-05-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210508_1337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client_client',
        ),
    ]
