# Generated by Django 3.2 on 2021-05-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField()),
                ('description', models.TextField(max_length=200)),
                ('categorie', models.CharField(max_length=30)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'client_Offre',
            },
        ),
    ]
