# Generated by Django 3.2 on 2021-05-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_offre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='id_client',
            new_name='client',
        ),
    ]
